# Generated by Django 4.1.7 on 2023-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ticket', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('sector', models.CharField(choices=[('TC', 'Technology'), ('BK', 'Banking'), ('FS', 'Fashion'), ('EG', 'Energy')], default='', max_length=2)),
            ],
        ),
    ]
