# Generated by Django 4.1.7 on 2023-03-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateInvestmentTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ticket', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('sector', models.CharField(choices=[('LG', 'Logistics'), ('SH', 'Shopping'), ('RS', 'Residential')], default='', max_length=2)),
            ],
        ),
    ]
