# Generated by Django 4.1.7 on 2023-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_realestateinvestmenttrust'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvestmenttrust',
            name='dividend',
            field=models.FloatField(default=0.0),
        ),
    ]
