# Generated by Django 4.1.7 on 2023-03-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_realestateinvestmenttrust_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(default=True)),
                ('reit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.realestateinvestmenttrust')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
